name = "SMLMBaGoL"
uuid = "70c4bcd9-ed9a-43d6-baf8-7d0db1eb70ee"
authors = ["klidke@unm.edu"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
